Repository pannlnwza/queue-management, pull requests merged in 2024-10, with the labels that each got.

#15 Initialize Django's project files
  README.md
  manage.py
  mysite/__init__.py
  mysite/asgi.py
  mysite/settings.py
  mysite/urls.py
  mysite/wsgi.py
  queue_manager/__init__.py
  queue_manager/admin.py
  queue_manager/apps.py
  queue_manager/models.py
  queue_manager/tests.py
  queue_manager/urls.py
  queue_manager/views.py
  requirements.txt
  sample.env
Labels: enhancement

#76 Feature/sse updates
  queue_manager/admin.py
  queue_manager/models.py
  queue_manager/services/__init__.py
  queue_manager/services/queue_stream.py
  queue_manager/templates/queue_manager/general_dashboard.html
  queue_manager/templates/queue_manager/index.html
  queue_manager/templates/queue_manager/manage_queues.html
  queue_manager/urls.py
  queue_manager/views.py
Labels: pull requests

#79 Bugfix/dashboard stats
  queue_manager/models.py
  queue_manager/services/queue_stream.py
  queue_manager/templates/queue_manager/general_dashboard.html
Labels: bug, pull requests

#78 Feature/queue categories
  mysite/settings.py
  mysite/urls.py
  queue_manager/forms.py
  queue_manager/migrations/0004_queue_status.py
  queue_manager/models.py
  queue_manager/static/queue_manager/images/bank.jpg
  queue_manager/static/queue_manager/images/bank_default_logo.jpg
  queue_manager/static/queue_manager/images/general.jpg
  queue_manager/static/queue_manager/images/general_default_logo.png
  queue_manager/static/queue_manager/images/hospital.jpg
  queue_manager/static/queue_manager/images/hospital_default_logo.jpg
  queue_manager/static/queue_manager/images/restaurant.jpg
  queue_manager/static/queue_manager/images/restaurant_default_logo.png
  queue_manager/static/queue_manager/images/service_center.jpg
  queue_manager/static/queue_manager/images/service_center_default_logo.png
  queue_manager/templates/queue_manager/all_queues.html
  queue_manager/templates/queue_manager/browse_queue.html
  queue_manager/templates/queue_manager/create_q.html
  queue_manager/templates/queue_manager/general_dashboard.html
  queue_manager/templates/queue_manager/list_queues.html
  queue_manager/tests/test_forms.py
  queue_manager/urls.py
  queue_manager/views.py
  requirements.txt
Labels: feature, pull requests

#83 Feature/notify participant
  .coveragerc
  queue_manager/admin.py
  queue_manager/forms.py
  queue_manager/migrations/0001_initial.py
  queue_manager/migrations/0002_alter_queue_estimated_wait_time_per_turn.py
  queue_manager/migrations/0003_alter_queue_estimated_wait_time_per_turn.py
  queue_manager/models.py
  queue_manager/services/data_stream.py
  queue_manager/static/queue_manager/js/queueDataStream.js
  queue_manager/templates/queue_manager/browse_queue.html
  queue_manager/templates/queue_manager/create_q.html
  queue_manager/templates/queue_manager/general_dashboard.html
  queue_manager/templates/queue_manager/index.html
  queue_manager/templates/queue_manager/list_queues.html
  queue_manager/templates/queue_manager/manage_queues.html
  queue_manager/tests/test_model.py
  queue_manager/tests/test_view.py
  queue_manager/urls.py
  queue_manager/views.py
  templates/base.html
Labels: feature

#86 Docs/installation guide
  .github/workflows/django.yml
  Installation.md
  README.md
  queue_manager/migrations/0001_initial.py
  queue_manager/migrations/0002_alter_queue_estimated_wait_time_per_turn.py
  queue_manager/migrations/0003_alter_queue_estimated_wait_time_per_turn.py
  queue_manager/migrations/__init__.py
Labels: documentation, pull requests
